# This is a basic workflow to help you get started with Actions

name: Build PDF from LaTeX

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Compile Latex Document
        uses: xu-cheng/latex-action@v2
        with: 
          root_file: main.tex
      - name: Setup gh-pages branch
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          cp ./main.pdf /tmp/main.pdf
          git switch --orphan gh-pages
          cp /tmp/main.pdf ./Ameya_Laad_CV.pdf
          git add ./Ameya_Laad_CV.pdf
          git commit -m "Commiting generated pdf"
          git push -u origin gh-pages
